config/routes.rb
Rails.application.routes.draw do #Worked with GPT to figure out the 'nesting' needed for Part II
  root 'places#index'
  resources :places do
    resources :entries, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  # talks to the "posts" table
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController #Made with GPT, Class notes, and requirements from HW 3
  def new
    @place = Place.find(params[:place_id])
    @entry = @place.entries.build
  end
  

  def create
    @place = Place.find(params[:place_id])
    @entry = @place.entries.build(entry_params)
    if @entry.save
      redirect_to place_path(@place)
    else
      render :new
    end
  end
  
  private
  
  def entry_params
    params.require(:entry).permit(:title, :description, :posted_on)
  end  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController #Built with the help of GPT 4.0 based on my class lecture notes and HW goals for user stories
  
  def index
    @places = Place.all
  end
  
  def show
    @place = Place.find(params[:id])
  end
  
  def new
    @place = Place.new
  end
  
  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to places_path
    else
      render :new
    end
  end
  
  private
  def place_params
    params.require(:place).permit(:name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/create.html.erb
<!--Lists entries Made with help of GPT based on my notes and assignment detail-->

<%= form_for([@place, @entry]) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
      <ul>
        <% @entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :posted_on %><br>
    <%= f.date_select :posted_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/new.html.erb
<!--Lists entries Made with help of GPT based on my notes and assignment detail-->

<%= form_for([@place, @entry]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :posted_on %><br>
    <%= f.date_select :posted_on %>
  </p>
  <%= f.submit "Save Entry" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/index.html.erb
<!--Lists places and links to each places show page and the new place form Made with help of GPT based on my notes and assignment detail-->
<h1 style="color: blue;">Places I've Been</h1> 
<ul>
  <% @places.each do |place| %>
    <li><%= link_to place.name, place_path(place) %></li>
  <% end %>
</ul>
<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<!--Form for creating a new place, made with help of GPT and class notes-->

<%= form_with model: @place, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div>
    <%= form.submit "Save" %>
  </div>
<% end %>
<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<!--Display place name and link back to places list.
 Made with help of GPT based on my notes and assignment detail-->

<h2 style="color: blue;"><%= @place.name %></h2>


<% @place.entries.order(posted_on: :desc).each do |entry| %>
  <div>
    <h4><%= entry.title %></h4>
    <p><small style="font-style: italic;"><%= entry.posted_on.strftime("%B %d, %Y") %></small></p> <!--Worked with GPT to get formatting perfect here-->
    <p><%= entry.description %></p>
  </div>
<% end %>



<h4>Options:</h4>
<%= link_to 'Back to Places', places_path %>
<br>
<%= link_to 'Add New Entry', new_place_entry_path(@place) %>